// Login
export const SIGN_IN = 'SIGN_IN'
export const SIGN_OUT = 'SIGN_OUT'

// User Profile
export const FETCH_PROFILE = 'FETCH_PROFILE'
export const LOAD_PROFILE = 'LOAD_PROFILE'

// Player
export const FETCH_PLAY_MUSIC = 'FETCH_PLAY_MUSIC'
export const LOAD_PLAY_MUSIC = 'LOAD_PLAY_MUSIC'
export const FETCH_PAUSE_MUSIC = 'FETCH_PAUSE_MUSIC'
export const LOAD_PAUSE_MUSIC = 'LOAD_PAUSE_MUSIC'
export const FETCH_SKIP_TO_NEXT_MUSIC = 'FETCH_SKIP_TO_NEXT_MUSIC'
export const LOAD_SKIP_TO_NEXT_MUSIC = 'LOAD_SKIP_TO_NEXT_MUSIC'
export const FETCH_SKIP_TO_PREVIOUS_MUSIC = 'FETCH_SKIP_TO_PREVIOUS_MUSIC'
export const LOAD_SKIP_TO_PREVIOUS_MUSIC = 'LOAD_SKIP_TO_PREVIOUS_MUSIC'
